# Generated by Cursor on 2026-03-09

from django.db import migrations


def seed_questions(apps, schema_editor):
    Question = apps.get_model("app", "Question")

    # Idempotent: only seed if there are no questions yet
    if Question.objects.exists():
        return

    Question.objects.bulk_create(
        [
            Question(
                topic="math",
                difficulty="easy",
                question_text="What is 7 + 5?",
                option_a="10",
                option_b="11",
                option_c="12",
                option_d="13",
                correct_answer="C",
                explanation="7 + 5 = 12.",
            ),
            Question(
                topic="math",
                difficulty="easy",
                question_text="Which fraction is equal to 0.5?",
                option_a="1/3",
                option_b="1/2",
                option_c="2/3",
                option_d="3/4",
                correct_answer="B",
                explanation="1/2 = 0.5.",
            ),
            Question(
                topic="math",
                difficulty="medium",
                question_text="Solve for x: 3x - 6 = 12",
                option_a="4",
                option_b="5",
                option_c="6",
                option_d="7",
                correct_answer="C",
                explanation="3x = 18 so x = 6.",
            ),
            Question(
                topic="logic",
                difficulty="easy",
                question_text="If all cats are mammals and all mammals are animals, then all cats are animals. This is an example of:",
                option_a="Induction",
                option_b="Deduction",
                option_c="Abduction",
                option_d="Contradiction",
                correct_answer="B",
                explanation="The conclusion follows necessarily from the premises (deduction).",
            ),
            Question(
                topic="logic",
                difficulty="medium",
                question_text="Which statement is the negation of: “All students passed the exam”?",
                option_a="No students passed the exam",
                option_b="Some students passed the exam",
                option_c="At least one student did not pass the exam",
                option_d="All students did not pass the exam",
                correct_answer="C",
                explanation="Negating “all” becomes “there exists at least one not”.",
            ),
            Question(
                topic="science",
                difficulty="easy",
                question_text="What is the chemical symbol for water?",
                option_a="O2",
                option_b="H2O",
                option_c="CO2",
                option_d="NaCl",
                correct_answer="B",
                explanation="Water is H2O.",
            ),
            Question(
                topic="science",
                difficulty="easy",
                question_text="Which planet is known as the Red Planet?",
                option_a="Venus",
                option_b="Mars",
                option_c="Jupiter",
                option_d="Mercury",
                correct_answer="B",
                explanation="Mars is called the Red Planet due to iron oxide on its surface.",
            ),
            Question(
                topic="science",
                difficulty="medium",
                question_text="Which part of the cell contains genetic material (DNA) in eukaryotes?",
                option_a="Ribosome",
                option_b="Cytoplasm",
                option_c="Nucleus",
                option_d="Cell membrane",
                correct_answer="C",
                explanation="In eukaryotic cells, DNA is stored in the nucleus.",
            ),
            Question(
                topic="math",
                difficulty="hard",
                question_text="What is the value of (2^5) × (2^3)?",
                option_a="2^8",
                option_b="2^15",
                option_c="2^2",
                option_d="2^5",
                correct_answer="A",
                explanation="Same base: add exponents (5 + 3 = 8).",
            ),
            Question(
                topic="logic",
                difficulty="hard",
                question_text="A statement is true, but its negation is also true. This situation is:",
                option_a="A tautology",
                option_b="A contradiction",
                option_c="Impossible in classical logic",
                option_d="An equivalence",
                correct_answer="C",
                explanation="In classical logic, a statement and its negation cannot both be true.",
            ),
        ]
    )


def unseed_questions(apps, schema_editor):
    Question = apps.get_model("app", "Question")
    # Only remove if they match our seeded topics; keep user-created data safe.
    Question.objects.filter(topic__in=["math", "science", "logic"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_question_studentprofile_quizsession_attempt"),
    ]

    operations = [
        migrations.RunPython(seed_questions, reverse_code=unseed_questions),
    ]

